### ISSUE TITLE
setup steps in config file generator

### ISSUE THREAD

**Issue by zeroXbrock** [zeroXbrock/contender#10]
- one-time setup section in a toml file that can be triggered from the CLI
- new command in contender-cli: `contender setup ./config.toml`
- support multiple function calls & contracts in one file

toml ideation:
```toml
[setup]
steps = [
...{existing layout}
]

[spam]
...{existing layout}
```

or possibly something like this:
```toml
[setup.step]
...{existing layout}
[setup.step]
...{existing layout}
[setup.step]
...{existing layout}

...
```
